export const RIME_KEY_MAP: Record<string, string | undefined> = {
	"Escape": "Escape",
	"F4": "F4",
	"Backspace": "BackSpace",
	"Delete": "Delete",
	"Tab": "Tab",
	"Enter": "Return",
	"Home": "Home",
	"End": "End",
	"PageUp": "Page_Up",
	"PageDown": "Page_Down",
	"ArrowUp": "Up",
	"ArrowRight": "Right",
	"ArrowDown": "Down",
	"ArrowLeft": "Left",
	"~": "asciitilde",
	"`": "quoteleft",
	"!": "exclam",
	"@": "at",
	"#": "numbersign",
	"$": "dollar",
	"%": "percent",
	"^": "asciicircum",
	"&": "ampersand",
	"*": "asterisk",
	"(": "parenleft",
	")": "parenright",
	"-": "minus",
	"_": "underscore",
	"+": "plus",
	"=": "equal",
	"{": "braceleft",
	"[": "bracketleft",
	"}": "braceright",
	"]": "bracketright",
	":": "colon",
	";": "semicolon",
	'"': "quotedbl",
	"'": "apostrophe",
	"|": "bar",
	"\\": "backslash",
	"<": "less",
	",": "comma",
	">": "greater",
	".": "period",
	"?": "question",
	"/": "slash",
	" ": "space",
};

export const ordinalSuffixes: Record<string, string | undefined> = {
	1: "st",
	2: "nd",
	3: "rd",
};
